apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tv5csmu7k-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tv5csmu7k-java-quarkus-gitops